### PR TITLE
Corald admin

### PR DESCRIPTION
**Pull request by jde**
This pr contains proxy routes for all the platform configuration endpoints. They are required for the coral-platform-admin application.

### CODE REVIEW

**Comment by dwhitena** [comment]
@jde The routes make sense to me, but just wondering about the purpose.  Is this for the configuration distribution stuff?  What exactly is meant by the "coral-platform-admin" app?  Is this what you showed me to help build the configuration?  Should these be publicly exposed via corald, or just connected directly to the admin app running on the same box?  Just trying to think through what we expose.  Thanks in advance for the clarification.

**Comment by jde** [comment]
Good questions all around. First, these routes will either require the highest level of authentication when available or be removed from public facing entirely when we go to beta. We may want to bring the FE app I'm referring to into the private network once it's set up.

For now, this is a tool that I'm working on in my spare time to make my day job easier.

My goals, in this order, are:
- to view raw configuration active in a Coral Platform install
- to view _interpreted_ configuration (aka, give a plain english language or graphical representation of what the json means)
- to be able to edit pieces of configuration
- to be able to export as a block all of the config at play
- to be able to import said block of config in a single file and have it sent to the appropriate platform endpoints

**Comment by dwhitena** [comment]
@jde Your goals make sense.  Are you just connecting to the services via the private network now?  What is the advantage of exposing these publicly (especially if they will likely be removed eventually)?  Or does it need to connect publically?

**Comment by jde** [comment]
This is going to live in the admin app that does moderation, etc... I was
aiming to strictly hit corald from that app from the beginning so that we
didn't need to refactor when we deploy later. I can see the argument for
wiring these directly as well.

*David Erwin*
Lead Engineer, The Coral Project / The New York Times

*917-687-6046
<https://en.wikipedia.org/wiki/Telephone#/media/File:Consolidated_Telephone_Co._ad_1886.jpg>
|
@daviderwin <https://twitter.com/daviderwin>
| https://github.com/coralproject <https://github.com/coralproject> *

On Thu, Oct 13, 2016 at 12:11 PM, Daniel Whitenack <notifications@github.com

**Comment by jde** [comment]
On second thought, it's just a matter of specifying a couple of host url config options on the front end.  With these in place we can easy toggle back and forth in configuration without needs for code changes.

No need for corald code. Closing.

**Pull request closed without merging**
